### ISSUE TITLE
Large File Silently Added To User Home Directory

### ISSUE THREAD

**Issue by DarioS** [VCCRI/Ularcirc#10]
I was wondering why I got an automatic disk quota warning and then I realised that clicking on Build Table button in Gene View tab creates a large binary file in the user's home directory in an invisible .cache folder.

```
$ ls -lht $HOME/.cache/BiocFileCache/ | head -n 2
total 570M
-rw-r----- 1 dario stgrad 570M Jan 14 11:20 608926b2a025_608926b2a025
```

Can there be some instructions in the vignette about how to change this to a different folder?

**Comment by davhum** [comment]
Hi Dario,

After a bit of searching I discovered that this file is generated by dplyr functions which in turn  use the BiocFileCache variables. I have discovered that you can reset the location by defining the unix variable XDG_CACHE_HOME. 

i.e. type the following line (and update temporary directory accordingly) in your .profile file so that it is always set.

set XDG_CACHE_HOME=/scratch/tmp

The temporary files will then start populating either directly the defined directory or in a BiocFileCache subdirectory of this directory. In fact probably best to create the  BiocFileCache
subdirectory.

I will add these details to the vignette and will close this thread when updated.

Note I have also addressed the browser() issues on the other thread but am still working through some minor warnings via devtools::build.

Regards,
D

**Comment by davhum** [comment]
New Vignette has been pushed onto github. Had some other build issues which are all resolved now.
